opening_hours_dict = {
    "Oslo Lokka": {"normal_hours": [12], "special_hours": [17]},
    "Oslo Storo": {"normal_hours": [11], "special_hours": [11]},
    "Oslo City": {"normal_hours": [12], "special_hours": [10]},
    "Oslo Torggata": {"normal_hours": [13], "special_hours": [17]},
    "Karl Johan": {"normal_hours": [12], "special_hours": [17]},
    "Fredrikstad": {"normal_hours": [11], "special_hours": [16]},
    "Stavanger": {"normal_hours": [12], "special_hours": [17]},
    "Bergen": {"normal_hours": [12], "special_hours": [17]},
    "Oslo Steen_Strom": {"normal_hours": [9], "special_hours": [8]},
    "Oslo Smestad": {"normal_hours": [7], "special_hours": [7]},
    "Sandnes": {"normal_hours": [11], "special_hours": [9]},
    "Restaurant": {"normal_hours": [13], "special_hours": [13]},
    "Fisketorget Utsalg": {"normal_hours": [7], "special_hours": [6]},
    "Trondheim": {"normal_hours": [12], "special_hours": [17]},
    "Åsane Storsenter": {"normal_hours": [12,11], "special_hours": [9]},
}

holiday_parameter_type_categorization = {
    "custom_regressor": "special",
    "covid_restriction_christmas": "special",
    "covid_loose_fall21": "special",
    "christmas_shopping": "seasonal",
    "sunshine_amount": "weather",
    "heavy_rain_fall_weekend": "weather",
    "heavy_rain_winter_weekday": "weather",
    "heavy_rain_winter_weekend": "weather",
    "non_heavy_rain_fall_weekend": "weather",
    "closed_jan": "special",
    "cruise_ship_arrivals": "event",
    "day_before_red_day": "event",
    "dec_holiday": "event",
    "easter": "event",
    "easter_lowsaturday": "event",
    "easter_mondaydayoff": "event",
    "eight_may": "event",
    "extra_regressors_multiplicative": "special",
    "fadder_week": "special",
    "fellesferie": "event",
    "first_may": "event",
    "firstweek_jan": "special",
    "high_weekend": "seasonal",
    "historical_sale": "special",
    "is_fellesferie": "seasonal",
    "is_specific_month": "special",
    "june_july": "special",
    "multiplicative_terms": "special",
    "new_year_eve": "event",
    "new_years_day": "event",
    "oslo_pride": "event",
    "outliers": "special",
    "pinse": "event",
    "rain_windy_weekend": "weather",
    "seventeenth_may": "event",
    "sunday_regressor": "special",
    "tons_of_rock": "event",
    "unexpected_closure": "special",
    "unknown_outliers": "special",
    "valentines_day": "event",
    "warm_and_dry": "weather",
    "weekendmiddec_21covid": "special",
    "weekly_fall_start": "special",
    "weekly_fellesferie": "special",
    "Gladmat":"event",
    "Last day of school":"event",
    "First day of school":"event"
}

article_supergroup_values = [
    "Øl",
    "Alcohol",
    "Beer",
    "Beer after 21",
    "Brennevin",
    "Cocktails",
    "Rusbrus/Cider",
    "Spirits",
    "Tequila",
    "Vin",
    "Wine",
    "Wine, Taco Tuesday",
]

holiday_names_negative=['Gladmat']